name: Syria News

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    steps:
      - name: Create FIREBASE_KEYS.env file
        run: echo "$FIREBASE_KEYS_PROD" > FIREBASE_KEYS.env
        env:
          FIREBASE_KEYS_PROD: ${{ secrets.FIREBASE_KEYS_PROD }}

      - name: Create google-services.json file
        run: echo "$GOOGLE_SERVICE_PROD" > android/app/google-services.json
        env:
          GOOGLE_SERVICE_PROD: ${{ secrets.GOOGLE_SERVICE_PROD }}

      - uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
        with:
          flutter_channel: stable

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: '**/*.md'
      modified_files_only: false